package ui.main;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import ui.table.TableCustom;

public class AddVendor extends javax.swing.JPanel{
    
    public AddVendor() {
        initComponents();
        
        JTableHeader theader = tableVendor.getTableHeader();
        theader.setFont(new java.awt.Font("Segoe UI", 0, 18)); 
        
        testData(tableVendor);
        TableCustom.apply(scrollPane_tableVendor, TableCustom.TableType.MULTI_LINE);
    }
    
    private void testData(JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addRow(new Object[]{ "Nguyễn Văn A", "Việt Nam"});
        model.addRow(new Object[]{ "Nguyễn Văn B", "Mỹ"});
        model.addRow(new Object[]{ "Nguyễn Văn C", "Pháp"});
        model.addRow(new Object[]{ "Nguyễn Văn D", "Hà Lan"});
        model.addRow(new Object[]{ "Nguyễn Văn E", "Thụy Sĩ"});
        model.addRow(new Object[]{ "Nguyễn Văn F", "Hàn Quốc"});
        model.addRow(new Object[]{ "Nguyễn Văn G", "Nhật Bản"});
        model.addRow(new Object[]{ "Nguyễn Văn H", "Bỉ"});
        model.addRow(new Object[]{ "Nguyễn Văn I", "Anh"});
        model.addRow(new Object[]{ "Nguyễn Văn K", "Australia"});
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCenter = new javax.swing.JPanel();
        scrollPane_tableVendor = new javax.swing.JScrollPane();
        tableVendor = new javax.swing.JTable();
        lbTitlePane = new javax.swing.JLabel();
        lbTitleTable = new javax.swing.JLabel();
        lbVendorName = new javax.swing.JLabel();
        lbCountry = new javax.swing.JLabel();
        btnAdd = new ui.button.Button();
        txtVendorName = new ui.textfield.TextField();
        cbCountry = new ui.combo_suggestion.ComboBoxSuggestion();

        setPreferredSize(new java.awt.Dimension(1620, 1000));
        setLayout(new java.awt.BorderLayout());

        pCenter.setBackground(new java.awt.Color(242, 249, 255));
        pCenter.setPreferredSize(new java.awt.Dimension(1600, 1000));

        scrollPane_tableVendor.setBackground(new java.awt.Color(221, 221, 221));
        scrollPane_tableVendor.setBorder(null);

        tableVendor.setBackground(new java.awt.Color(242, 249, 255));
        tableVendor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableVendor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Quốc gia"
            }
        ));
        tableVendor.setGridColor(new java.awt.Color(218, 247, 249));
        scrollPane_tableVendor.setViewportView(tableVendor);

        lbTitlePane.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbTitlePane.setForeground(new java.awt.Color(102, 204, 255));
        lbTitlePane.setText("THÔNG TIN NHÀ CUNG CẤP");

        lbTitleTable.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitleTable.setForeground(new java.awt.Color(102, 204, 255));
        lbTitleTable.setText("DANH SÁCH NHÀ CUNG CẤP");

        lbVendorName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbVendorName.setText("Tên nhà cung cấp");

        lbCountry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbCountry.setText("Quốc gia ");

        btnAdd.setBackground(new java.awt.Color(5, 146, 57));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Thêm");
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtVendorName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVendorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendorNameActionPerformed(evt);
            }
        });

        cbCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anh", "Australia", "Ấn độ", "Bỉ", "Đan Mạch", "Đức", "Hà Lan", "Hàn Quốc", "Ireland", "Mỹ", "Nhật", "Pháp", "Thụy Sĩ", "Trung Quốc", "Việt Nam" }));
        cbCountry.setSelectedIndex(-1);
        cbCountry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pCenterLayout = new javax.swing.GroupLayout(pCenter);
        pCenter.setLayout(pCenterLayout);
        pCenterLayout.setHorizontalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitleTable)
                .addGap(643, 643, 643))
            .addGroup(pCenterLayout.createSequentialGroup()
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCenterLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pCenterLayout.createSequentialGroup()
                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbVendorName)
                                    .addComponent(lbCountry))
                                .addGap(37, 37, 37)
                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pCenterLayout.createSequentialGroup()
                                        .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(scrollPane_tableVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 1458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pCenterLayout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addComponent(lbTitlePane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pCenterLayout.setVerticalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCenterLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbTitlePane, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVendorName)
                    .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCountry)
                    .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(lbTitleTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPane_tableVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        add(pCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtVendorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendorNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.button.Button btnAdd;
    private ui.combo_suggestion.ComboBoxSuggestion cbCountry;
    private javax.swing.JLabel lbCountry;
    private javax.swing.JLabel lbTitlePane;
    private javax.swing.JLabel lbTitleTable;
    private javax.swing.JLabel lbVendorName;
    private javax.swing.JPanel pCenter;
    private javax.swing.JScrollPane scrollPane_tableVendor;
    private javax.swing.JTable tableVendor;
    private ui.textfield.TextField txtVendorName;
    // End of variables declaration//GEN-END:variables
}
