package ui.main;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import ui.table.TableCustom;

public class OrderHistory extends javax.swing.JPanel{
    
    public OrderHistory() {
        initComponents();
        
        JTableHeader theader = tableOrder.getTableHeader();
        theader.setFont(new java.awt.Font("Segoe UI", 0, 18));  
        testData(tableOrder);
        TableCustom.apply(jScrollPane_tableOrder, TableCustom.TableType.MULTI_LINE);
    }
    
    private void testData(JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addRow(new Object[]{"HD001", "Nguyễn Văn A", "Trần Văn B", "2024-10-15 10:00", "Online", "10%", "900.000"});
        model.addRow(new Object[]{"HD002", "Lê Thị B", "Trần Văn C", "2024-10-15 11:00", "Trực tiếp", "5%", "800.000"});
        model.addRow(new Object[]{"HD003", "Trần Văn D", "Võ Hoàng E", "2024-10-15 12:00", "Online", "15%", "1.200.000"});
        model.addRow(new Object[]{"HD004", "Nguyễn Văn F", "Lê Văn G", "2024-10-15 13:00", "Trực tiếp", "10%", "950.000"});
        model.addRow(new Object[]{"HD005", "Nguyễn Thị H", "Trần Văn I", "2024-10-15 14:00", "Online", "Không có", "1.500.000"});
        model.addRow(new Object[]{"HD006", "Võ Văn J", "Nguyễn Văn K", "2024-10-15 15:00", "Trực tiếp", "20%", "1.800.000"});
        model.addRow(new Object[]{"HD007", "Lê Thị M", "Trần Thị N", "2024-10-15 16:00", "Online", "5%", "700.000"});
        model.addRow(new Object[]{"HD008", "Phạm Văn O", "Nguyễn Văn P", "2024-10-15 17:00", "Trực tiếp", "10%", "1.000.000"});
        model.addRow(new Object[]{"HD009", "Trần Văn Q", "Lê Văn R", "2024-10-15 18:00", "Online", "10%", "850.000"});
        model.addRow(new Object[]{"HD010", "Nguyễn Thị S", "Võ Văn T", "2024-10-15 19:00", "Trực tiếp", "15%", "1.300.000"});
        model.addRow(new Object[]{"HD001", "Nguyễn Văn A", "Trần Văn B", "2024-10-15 10:00", "Online", "10%", "900.000"});
        model.addRow(new Object[]{"HD002", "Lê Thị B", "Trần Văn C", "2024-10-15 11:00", "Trực tiếp", "5%", "800.000"});
        model.addRow(new Object[]{"HD003", "Trần Văn D", "Võ Hoàng E", "2024-10-15 12:00", "Online", "15%", "1.200.000"});
        model.addRow(new Object[]{"HD004", "Nguyễn Văn F", "Lê Văn G", "2024-10-15 13:00", "Trực tiếp", "10%", "950.000"});
        model.addRow(new Object[]{"HD005", "Nguyễn Thị H", "Trần Văn I", "2024-10-15 14:00", "Online", "Không có", "1.500.000"});
        model.addRow(new Object[]{"HD006", "Võ Văn J", "Nguyễn Văn K", "2024-10-15 15:00", "Trực tiếp", "20%", "1.800.000"});
        model.addRow(new Object[]{"HD007", "Lê Thị M", "Trần Thị N", "2024-10-15 16:00", "Online", "5%", "700.000"});
        model.addRow(new Object[]{"HD008", "Phạm Văn O", "Nguyễn Văn P", "2024-10-15 17:00", "Trực tiếp", "10%", "1.000.000"});
        model.addRow(new Object[]{"HD009", "Trần Văn Q", "Lê Văn R", "2024-10-15 18:00", "Online", "10%", "850.000"});
        model.addRow(new Object[]{"HD010", "Nguyễn Thị S", "Võ Văn T", "2024-10-15 19:00", "Trực tiếp", "15%", "1.300.000"});
        model.addRow(new Object[]{"HD001", "Nguyễn Văn A", "Trần Văn B", "2024-10-15 10:00", "Online", "10%", "900.000"});
        model.addRow(new Object[]{"HD002", "Lê Thị B", "Trần Văn C", "2024-10-15 11:00", "Trực tiếp", "5%", "800.000"});
        model.addRow(new Object[]{"HD003", "Trần Văn D", "Võ Hoàng E", "2024-10-15 12:00", "Online", "15%", "1.200.000"});
        model.addRow(new Object[]{"HD004", "Nguyễn Văn F", "Lê Văn G", "2024-10-15 13:00", "Trực tiếp", "10%", "950.000"});
        model.addRow(new Object[]{"HD005", "Nguyễn Thị H", "Trần Văn I", "2024-10-15 14:00", "Online", "Không có", "1.500.000"});
        model.addRow(new Object[]{"HD006", "Võ Văn J", "Nguyễn Văn K", "2024-10-15 15:00", "Trực tiếp", "20%", "1.800.000"});
        model.addRow(new Object[]{"HD007", "Lê Thị M", "Trần Thị N", "2024-10-15 16:00", "Online", "5%", "700.000"});
        model.addRow(new Object[]{"HD008", "Phạm Văn O", "Nguyễn Văn P", "2024-10-15 17:00", "Trực tiếp", "10%", "1.000.000"});
        model.addRow(new Object[]{"HD009", "Trần Văn Q", "Lê Văn R", "2024-10-15 18:00", "Online", "10%", "850.000"});
        model.addRow(new Object[]{"HD010", "Nguyễn Thị S", "Võ Văn T", "2024-10-15 19:00", "Trực tiếp", "15%", "1.300.000"});

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new ui.datechooser.DateChooser();
        pCenter = new javax.swing.JPanel();
        txtSearch = new ui.textfield.TextField();
        btnCalendar = new ui.button.Button();
        btnAdd = new ui.button.Button();
        btnLoad = new ui.button.Button();
        cbbSaler = new ui.combobox.Combobox();
        cbbTime = new ui.combobox.Combobox();
        cbbMethod = new ui.combobox.Combobox();
        tableScrollButton_Order = new ui.table.TableScrollButton();
        jScrollPane_tableOrder = new javax.swing.JScrollPane();
        tableOrder = new javax.swing.JTable();

        date.setForeground(new java.awt.Color(102, 204, 255));
        date.setTextRefernce(txtSearch);

        setPreferredSize(new java.awt.Dimension(1620, 1000));
        setLayout(new java.awt.BorderLayout());

        pCenter.setBackground(new java.awt.Color(242, 249, 255));
        pCenter.setPreferredSize(new java.awt.Dimension(1600, 1000));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSearch.setMargin(new java.awt.Insets(3, 6, 3, 6));
        txtSearch.setName(""); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnCalendar.setBackground(new java.awt.Color(221, 221, 221));
        btnCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/button/calendar.png"))); // NOI18N
        btnCalendar.setPreferredSize(new java.awt.Dimension(64, 64));
        btnCalendar.setRound(20);
        btnCalendar.setShadowColor(new java.awt.Color(255, 255, 255));
        btnCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(5, 146, 57));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Tạo hóa đơn");
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setIconTextGap(2);
        btnAdd.setPreferredSize(new java.awt.Dimension(64, 64));
        btnAdd.setRound(30);
        btnAdd.setShadowColor(new java.awt.Color(0, 0, 0));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnLoad.setBackground(new java.awt.Color(5, 146, 57));
        btnLoad.setForeground(new java.awt.Color(255, 255, 255));
        btnLoad.setText("Làm mới");
        btnLoad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLoad.setIconTextGap(2);
        btnLoad.setPreferredSize(new java.awt.Dimension(64, 64));
        btnLoad.setRound(30);
        btnLoad.setShadowColor(new java.awt.Color(0, 0, 0));
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        cbbSaler.setBackground(new java.awt.Color(242, 249, 255));
        cbbSaler.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbbSaler.setForeground(new java.awt.Color(102, 102, 102));
        cbbSaler.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Nguyễn Thị Mỹ Duyên", "Huỳnh Thanh Giang", "Phan Phước Hiệp", "Hồ Quang Nhân" }));
        cbbSaler.setSelectedIndex(-1);
        cbbSaler.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbbSaler.setLabeText("Người bán");
        cbbSaler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSalerActionPerformed(evt);
            }
        });

        cbbTime.setBackground(new java.awt.Color(242, 249, 255));
        cbbTime.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbbTime.setForeground(new java.awt.Color(102, 102, 102));
        cbbTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Tuần này", "Tuần trước", "Tháng này", "Tháng trước" }));
        cbbTime.setSelectedIndex(-1);
        cbbTime.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbbTime.setLabeText("Thời gian");
        cbbTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTimeActionPerformed(evt);
            }
        });

        cbbMethod.setBackground(new java.awt.Color(242, 249, 255));
        cbbMethod.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cbbMethod.setForeground(new java.awt.Color(102, 102, 102));
        cbbMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả", "Theo đơn", "Không theo đơn" }));
        cbbMethod.setSelectedIndex(-1);
        cbbMethod.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbbMethod.setLabeText("Hình thức");
        cbbMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMethodActionPerformed(evt);
            }
        });

        tableOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Khách hàng", "Người tạo", "Thời gian", "Hình thức", "Khuyến mãi", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane_tableOrder.setViewportView(tableOrder);

        javax.swing.GroupLayout pCenterLayout = new javax.swing.GroupLayout(pCenter);
        pCenter.setLayout(pCenterLayout);
        pCenterLayout.setHorizontalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCenterLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCenterLayout.createSequentialGroup()
                        .addComponent(jScrollPane_tableOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 1575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(pCenterLayout.createSequentialGroup()
                        .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pCenterLayout.createSequentialGroup()
                                .addComponent(cbbSaler, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(cbbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(cbbMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pCenterLayout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                    .addContainerGap(22, Short.MAX_VALUE)
                    .addComponent(tableScrollButton_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 1577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );
        pCenterLayout.setVerticalGroup(
            pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCenterLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCenterLayout.createSequentialGroup()
                        .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                        .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbSaler, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane_tableOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pCenterLayout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(tableScrollButton_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );

        add(pCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarActionPerformed
        // TODO add your handling code here:
        date.showPopup();
    }//GEN-LAST:event_btnCalendarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadActionPerformed

    private void cbbSalerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSalerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbSalerActionPerformed

    private void cbbTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTimeActionPerformed

    private void cbbMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMethodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.button.Button btnAdd;
    private ui.button.Button btnCalendar;
    private ui.button.Button btnLoad;
    private ui.combobox.Combobox cbbMethod;
    private ui.combobox.Combobox cbbSaler;
    private ui.combobox.Combobox cbbTime;
    private ui.datechooser.DateChooser date;
    private javax.swing.JScrollPane jScrollPane_tableOrder;
    private javax.swing.JPanel pCenter;
    private javax.swing.JTable tableOrder;
    private ui.table.TableScrollButton tableScrollButton_Order;
    private ui.textfield.TextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
